input: touchscreen: squash: import gt9x_2.4 driver
Squashed commit of the following:

commit 835f659b492fc4e694100d49eaa412135a7fc2e9
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Sun Apr 8 14:49:45 2018 -0700

    Fix all outstanding GCC warnings

    https://toolchains.bootlin.com
    https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/

    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

commit dd9a1c4ccdf9f5c1a9b1f62f1ffdbd110f234181
Author: Yaroslav Furman <yaro330@gmail.com>
Date:   Wed Nov 14 18:33:38 2018 +0300

    input: touchscreen: do not select Synaptics by default

    Why?..

    Signed-off-by: Yaroslav Furman <yaro330@gmail.com>
    Signed-off-by: Subhajeet Muhuri <kenny3fcb@gmail.com>

commit 03661ff748ceaf636273a513d6002fc6db820728
Author: Yaroslav Furman <yaro330@gmail.com>
Date:   Wed Oct 31 12:24:58 2018 +0300

    gt9x_2.4: Disable FW update

    * It fails every time
    * Attempts to force update
    * Apparently breaks touchscreens for some users
    * Properly ifdef it so it won't fuck up build

    Signed-off-by: Yaroslav Furman <yaro330@gmail.com>
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 4fc0d80f3e20a77ac8ba27f7a501b5bf0a734a45
Author: Yaroslav Furman <yaro330@gmail.com>
Date:   Fri Jun 14 09:44:27 2019 +0530

    gt9xx: Don't return error when fw check fails

     * It is broken in some refurbished devices after k4.4 upgrade,
       but touchscreen works fine so why even bother..

    Change-Id: I167be7b1c282d5f3c90db0a131206b443da3a170

commit 70f943a9eda28d563efe379631fb43355ae614e6
Author: Davide Garberi <dade.garberi@gmail.com>
Date:   Wed Sep 19 15:57:36 2018 +0200

    gt9x_2.4: Remove unused variables

    drivers/input/touchscreen/gt9x_2.4/gt9xx.c: In function 'gtp_i2c_read':
    drivers/input/touchscreen/gt9x_2.4/gt9xx.c:115:25: error: unused variable 'ts' [-Werror=unused-variable]
      struct goodix_ts_data *ts = i2c_get_clientdata(client);
                             ^~
    drivers/input/touchscreen/gt9x_2.4/gt9xx.c: In function 'gtp_i2c_write':
    drivers/input/touchscreen/gt9x_2.4/gt9xx.c:160:5: error: unused variable 'retries' [-Werror=unused-variable]
      u8 retries;
         ^~~~~~~
    drivers/input/touchscreen/gt9x_2.4/gt9xx.c:158:25: error: unused variable 'ts' [-Werror=unused-variable]
      struct goodix_ts_data *ts = i2c_get_clientdata(client);
                             ^~
    drivers/input/touchscreen/gt9x_2.4/gt9xx.c: In function 'goodix_ts_suspend':
    drivers/input/touchscreen/gt9x_2.4/gt9xx.c:1911:16: error: unused variable 'i' [-Werror=unused-variable]
      int ret = -1, i;

    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 67d70f35a420f0a5602045d9a1fd79a401e95704
Author: YaroST12 <yaro330@gmail.com>
Date:   Sun Mar 18 15:38:37 2018 +0300

    gt9x_2.4: Fix slow touchscreen wakeup

     * We don't need this complicated system. It works fine even when simplified. This speeds up screen and touchscreen wakeup when woken up by fingerprint scaner, power button and etc...

    Signed-off-by: YaroST12 <yaro330@gmail.com>
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 09732a9ade5960a75cc95e3f13151bbec5143690
Author: YaroST12 <yaro330@gmail.com>
Date:   Sun Mar 18 15:10:03 2018 +0300

    gt9x_2.4: remove usage of init_done

     * Slows down touchscreen wakeup

    Signed-off-by: YaroST12 <yaro330@gmail.com>
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 41c81b7245561dd5a3992eb408036ed7cfb8fe73
Author: Shantanu Jain <shjain@codeaurora.org>
Date:   Fri Sep 27 12:00:39 2013 +0530

    input: touchscreen: Clean code for i2c_read and i2c_write

    Use standard initializer code in gtp_i2c_read and
    gtp_i2c_write functions for Goodix touchscreen driver.

    CRs-fixed: 549289
    Change-Id: Id954be61a0b4596339a659928fb630c5c5538a9a
    Signed-off-by: Shantanu Jain <shjain@codeaurora.org>
    Signed-off-by: Sudhakar Manapati <smanap@codeaurora.org>
    Signed-off-by: YaroST12 <yaro330@gmail.com>
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit ee213016247b2c8a514d97bc89ee3ae1251569c4
Author: Shantanu Jain <shjain@codeaurora.org>
Date:   Mon Aug 5 16:52:47 2013 +0530

    input: touchscreen: release all touches before suspend

    release all touches before going to suspend for goodix
    gt9xx TS driver.

    This patch is propagated from msm-3.4 kernel
    (commit: a1b5c4559026d9ddc789f64e17c1ade0a281d372
    input: touchscreen: release all touches before suspend)

    Change-Id: Ia3446f3c23be4fe29bfea5f85b22e8b903cffb9e
    Signed-off-by: Shantanu Jain <shjain@codeaurora.org>
    Signed-off-by: Sudhakar Manapati <smanap@codeaurora.org>
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit a4f2d8f0bf9ae695070c27e32f782efa610bc983
Author: Davide Garberi <dade.garberi@gmail.com>
Date:   Sat Feb 3 14:35:31 2018 +0100

    gt9x_2.4: Automatically fix spaces indentation

    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 80c38eebb65d439340ed35ad750d2d5fa487e1e3
Author: Davide Garberi <dade.garberi@gmail.com>
Date:   Sat Feb 3 14:28:00 2018 +0100

    gt9x_2.4: Remove the GT9XXF functions completely

    * It's being completely unused

    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 0b0c499002bd3d3fadbba4278c3e8e24727017c8
Author: Fedor917 <cryscript@gmail.com>
Date:   Sun Jan 22 04:16:14 2017 +0700

    gt9x_2.4: Fix touchscreen not working in AROMA and MultiROM BootUI

    Signed-off-by: dd3boh <dade.garberi@gmail.com>
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 10779a1c63c3968c39f5bbc0484fd4f3c385b298
Author: davidevinavil <davidevinavil@gmail.com>
Date:   Mon Jun 19 02:40:17 2017 +0200

    gt9xx: Fix proximity check over dt2w

    Change-Id: I988c25b85dca381b73fb47b06276bc7fa1ad8772
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

commit 2f5a5590efa70e483b5a47202c750f8bfd0bfac4
Author: Faiz Authar <faizauthar@gmail.com>
Date:   Wed Apr 26 12:37:52 2017 +0700

    drivers: input: Import touchscreen changes from ZUK

    ajaivasudeve:
    > import just the gt9x_2.4 driver

    Change-Id: I8a424d880cd6569c67d0fa836291fa1310ad85e7
    Signed-off-by: Davide Garberi <dade.garberi@gmail.com>

Co-authored-By: Faiz Authar <faizauthar@gmail.com>
Co-authored-By: Davide Garberi <dade.garberi@gmail.com>
Co-authored-By: dmd79 [github.com/dmd79]
Co-authored-By: Yaroslav Furman <yaro330@gmail.com>
Co-authored-By: Nathan Chancellor <natechancellor@gmail.com>
Co-authored-By: ajaivasudeve <ajaivasudeve@gmail.com>